# livekit-server Helm values — Bank EKS (air-gapped)
replicaCount: 1


terminationGracePeriodSeconds: 18000


image:
  repository: public.ecr.aws/u7h9i3k7/livekit/livekit-server
  tag: latest
  pullPolicy: IfNotPresent


livekit:
  log_level: debug
  port: 30080
  prometheus_port: 6789


  rtc:
    use_external_ip: false
    node_ip: "<TURN_NLB_PRIVATE_DNS>"
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7881
    stun_servers: []
    ice_lite: true


  redis:
    address: "master.livekit-redis.hxh1sa.aps1.cache.amazonaws.com:6379"


  room:
    enable_remote_unmute: true


  keys:
    apikey-f08c885db1aa9798: "ZCoo5vnP1ec1dFzAluM0SWneFH0zmokm7DjJmQecRk6zIFifHF9rzO73DlNcoJYQ"
  webhook:
    api_key: "apikey-f08c885db1aa9798"
    urls:
      - "http://convogent-voice.convogent.svc.cluster.local:9000/voice_service/livekit/webhook"


  extraEnv:
    - name: PORT
      value: "30080"


  turn:
    enabled: true
    domain: "<TURN_NLB_PRIVATE_DNS>"
    tls_port: 5349
    udp_port: 3478
    external_tls: true
    cert_file: /tls/tls.crt
    key_file: /tls/tls.key
    relay_range_start: 30000
    relay_range_end: 50000


ingress:
  enabled: false


loadBalancer:
  type: disable
  tls:
    - secretName: turn-tls-dummy


autoscaling:
  enabled: false


podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "6789"


podHostNetwork: false


nodeSelector:
  workload: livekit-server


tolerations:
  - key: "workload"
    operator: "Equal"
    value: "livekit-server"
    effect: "NoSchedule"


resources:
  requests:
    cpu: "1500m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"