# livekit-server Helm values — Bank EKS (air-gapped)
replicaCount: 3

terminationGracePeriodSeconds: 18000

image:
  repository: 273354645607.dkr.ecr.ap-south-1.amazonaws.com/livekit-server
  tag: v1.9.12
  pullPolicy: IfNotPresent

livekit:
  log_level: debug
  port: 30080
  prometheus_port: 6789

  rtc:
    use_external_ip: false
    node_ip: "<TURN_NLB_EIP>"
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7881
    stun_servers: []
    ice_lite: true

  redis:
    address: "<REDIS_ENDPOINT>:6379"

  room:
    enable_remote_unmute: true

  keys:
    <LIVEKIT_API_KEY>: "<LIVEKIT_API_SECRET>"

  webhook:
    api_key: "<LIVEKIT_API_KEY>"
    urls:
      - "https://<AGENT_DOMAIN>/voice_service/livekit/webhook"

  extraEnv:
    - name: PORT
      value: "30080"

  turn:
    enabled: true
    domain: "<TURN_DOMAIN>"
    tls_port: 5349
    udp_port: 3478
    external_tls: true
    cert_file: /tls/tls.crt
    key_file: /tls/tls.key
    relay_range_start: 30000
    relay_range_end: 50000

ingress:
  enabled: false

loadBalancer:
  type: disable
  tls:
    - secretName: turn-tls-dummy

autoscaling:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "6789"

podHostNetwork: false

nodeSelector:
  workload: livekit-core

tolerations:
  - key: "workload"
    operator: "Equal"
    value: "livekit-core"
    effect: "NoSchedule"

resources:
  requests:
    cpu: "1500m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"
