{{- if .Values.voiceService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "convogent-voice.name" . }}
  namespace: {{ include "convogent-voice.namespace" . }}
  labels:
    {{- include "convogent-voice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.voiceService.service.type }}
  ports:
    - port: {{ .Values.voiceService.service.port }}
      targetPort: {{ .Values.voiceService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "convogent-voice.selectorLabels" . | nindent 4 }}
{{- end }}
