apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-sip-config
  namespace: livekit
data:
  SIP_CONFIG_BODY: |
    log_level: debug

    api_key: "apikey-f08c885db1aa9798"
    api_secret: "ZCoo5vnP1ec1dFzAluM0SWneFH0zmokm7DjJmQecRk6zIFifHF9rzO73DlNcoJYQ"

    ws_url: "ws://livekit-server.livekit.svc.cluster.local:80"

    redis:
      address: "master.livekit-redis.hxh1sa.aps1.cache.amazonaws.com:6379"

    sip_port: 5060
    rtp_port_range_start: 10000
    rtp_port_range_end: 20000
    use_external_ip: false
    prometheus_port: 6789
