apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-sip-config
  namespace: livekit
data:
  SIP_CONFIG_BODY: |
    log_level: debug

    api_key: "<LIVEKIT_API_KEY>"
    api_secret: "<LIVEKIT_API_SECRET>"

    ws_url: "wss://<LIVEKIT_DOMAIN>"

    redis:
      address: "<REDIS_ENDPOINT>:6379"

    sip_port: 5060
    rtp_port_range_start: 10000
    rtp_port_range_end: 20000
    use_external_ip: true
    prometheus_port: 6789
