{{- if and .Values.evalService.enabled ((.Values.evalService.pdb).enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "convogent-eval.name" . }}
  namespace: {{ include "convogent-eval.namespace" . }}
  labels:
    {{- include "convogent-eval.labels" . | nindent 4 }}
spec:
  {{- if .Values.evalService.pdb.minAvailable }}
  minAvailable: {{ .Values.evalService.pdb.minAvailable }}
  {{- else if .Values.evalService.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.evalService.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "convogent-eval.selectorLabels" . | nindent 6 }}
{{- end }}
