{{- if .Values.evalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "convogent-eval.name" . }}
  namespace: {{ include "convogent-eval.namespace" . }}
  labels:
    {{- include "convogent-eval.labels" . | nindent 4 }}
spec:
  type: {{ .Values.evalService.service.type }}
  ports:
    - port: {{ .Values.evalService.service.port }}
      targetPort: {{ .Values.evalService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "convogent-eval.selectorLabels" . | nindent 4 }}
{{- end }}
