apiVersion: v2
name: convogent-backend
description: Convogent Backend API service
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - convogentv2
  - backend
maintainers:
  - name: Convogentv2
    email: team@convogentv2.com
